# Generated by Django 3.2.4 on 2021-07-11 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_review_book_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
